# Generated by Django 3.0.5 on 2020-04-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
